### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by zengjia1** [lyvd/taming-bad-python-packages-blog-post#1]
I noticed that the dataset only contains package names, but, many malicious packages have been removed from pypi and can no longer be downloaded. I am wondering if you could upload a more detailed dataset. I promise that they will be used for research purposes only.
Thank you very much. Looking forward to your early reply.

**Comment by lyvd** [comment]
Hello, I cannot share the samples on my behalf, please contact the authors of the datasets. 

- Backstabbers-Knife-Collection: https://dasfreak.github.io/Backstabbers-Knife-Collection/
- MalOSS: https://github.com/osssanitizer/maloss (There is a Google form at https://forms.gle/MwsN6fydMRWL1j5V9)

Hope this helps.

**Comment by zengjia1** [comment]
Thank you very much.

**Comment by lyvd** [comment]
You're welcome!
